### ISSUE TITLE
Ubuntu 18.04 64bit: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by EarthSenseOli** [urschrei/convertbng#6] opened 2020-05-22 17:21 UTC
I have been using convertbng on a windows machine successfully and I attempted to move my code onto an ubuntu server and get an "Illegal instruction (core dumped)" error every time I try to call any function in this library.

I even tried with a very simple test case and then had the same issue. The following code works fine on the windows device but not on the linux server:

```
from convertbng.util import convert_bng
convert_bng([-1.89983], [52.48142])
```

Cheers,

**Comment by urschrei** [comment] 2020-05-22 18:18
Without more information, I can't really diagnose this:

- What Python version are you using? How did you install it? Are you running in a virtualenv?
- Do any other Python programs display this error (particularly, anything running Numpy – please test this)
- What CPU are you running? Try `less /proc/cpuinfo` and paste the output.

**Comment by EarthSenseOli** [comment] 2020-05-26 09:02
Sure:

- Python 3.6.9
- Python was installed as part of an AWS installation
- ConvertBNG was then installed using pip
- No virtualenv
- Not having any issues with other Python programs. I've done some testing with Numpy and did not have any problems, but will keep testing. Ran the full test suite with np.test('full') and this ran successfully.

**Output from test suite**
9944 passed, 567 skipped, 20 xfailed, 1 xpassed in 429.94s (0:07:09)
True


**CPU Info:**
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7571
stepping        : 2
microcode       : 0x8001250
cpu MHz         : 2199.952
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4399.90
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7571
stepping        : 2
microcode       : 0x8001250
cpu MHz         : 2199.952
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 1
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes


Cheers,

**Comment by urschrei** [comment] 2020-05-26 09:06
Great, thanks! When you say AWS, I assume it's EC2, but if you can let me know the instance type etc it'll make attempts to reproduce the problem a lot easier.

**Comment by EarthSenseOli** [comment] 2020-05-26 09:10
Yes EC2. It's a t3a.large with this AMI
http://cloud-images-archive.ubuntu.com/releases/bionic/release-20180522/

**Comment by metaljoe** [comment] 2020-07-28 08:51
Has there been any progress on this issue?

I've been using convertbng on MacOS to bulk convert a load of Northings/Eastings from government data to Lat/Long, and it works great (thanks!). However, we've had the same issue as above with an illegal instruction when running on a Docker container based on Ubuntu Xenial/16.04 (64-bit). It fails with convert_bng and convert_lonlat, even if empty coordinate lists are supplied.

* Python 3.6.11
* installed from the deadsnakes PPA
* code is running in a virtualenv created by python3.6 -m venv
* no issues with other code, no issues with numpy as far as I can tell

CPU - first example I have to hand:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
stepping	: 1
cpu MHz		: 2193.230
cache size	: 6144 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		:
bogomips	: 4386.46
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
stepping	: 1
cpu MHz		: 2193.230
cache size	: 6144 KB
physical id	: 1
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		:
bogomips	: 4347.75
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
stepping	: 1
cpu MHz		: 2193.230
cache size	: 6144 KB
physical id	: 2
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		:
bogomips	: 5139.29
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 70
model name	: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
stepping	: 1
cpu MHz		: 2193.230
cache size	: 6144 KB
physical id	: 3
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		:
bogomips	: 4244.09
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**Comment by filipafcastro** [comment] 2020-07-29 09:18
Same problem here when using 3.6.9 with Ubuntu 18.04, being it in a virtual environment or not.

**Comment by urschrei** [comment] 2020-07-30 10:25
@metaljoe @filipafcastro thanks for the bug reports - I'll try to make some progress on this, but at the moment I have no idea what could be causing it, and I'm regrettably extremely time-constrained for the foreseeable future. It's possible that this is a Python 3.6 issue, and I don't want to anticipate that, but if it's possible for either of you to reproduce the error using 3.7 or 3.8 that would be a big help.

**Comment by metaljoe** [comment] 2020-07-30 11:02
@urschrei No worries, I completely understand about being time-constrained.

I've just built versions of my container with Python 3.7.8 and 3.8.5 (deadsnakes PPA) and the illegal instruction is raised for both versions. It doesn't look to be specific to Python 3.6. Hope that helps.

**Comment by urschrei** [comment] 2020-07-30 11:05
@metaljoe OK great. I'll have a think about how best to diagnose this. Another question: can you reproduce this without running under Docker?

**Comment by hellicott** [comment] 2020-08-25 09:11
Any updates on this? I'm getting this same issue on an Azure batch 'Canonical UbuntuServer 18.04-LTS' node.

**Comment by utkarsh2102** [comment] 2020-09-18 14:29
I am running Debian, python3.8.x version.
And here's a quick reproducer:
```
>>> from convertbng.util import convert_bng, convert_lonlat
>>> import numpy as np
>>> lons = [1.0, 3.0]
>>> lats = [2.0, 4.0]
>>> lons
[1.0, 3.0]
>>> lats
[2.0, 4.0]
>>> res_list = convert_bng(lons, lats)
[1]    32564 illegal hardware instruction  python3
```

Hope that helps.

**Comment by utkarsh2102** [comment] 2020-09-18 14:30
@urschrei, I get this whilst running on host or anywhere^^.
Could be reproduced in almost any container. LXC, docker, whatever :)

**Comment by urschrei** [comment] 2020-09-18 14:44
@utkarsh2102 Could you try installing version 0.6.10 from PyPI instead, and seeing if causes the same error?

**Comment by utkarsh2102** [comment] 2020-09-18 15:23
Hello @urschrei,

This is weird, I get:
`ERROR: Could not find a version that satisfies the requirement convertbng==0.6.10 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.7, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.6.17)`
`ERROR: No matching distribution found for convertbng==0.6.10`

**Comment by urschrei** [comment] 2020-09-18 15:51
@utkarsh2102 Hmm. 0.4.14 will also work as a candidate.

**Comment by utkarsh2102** [comment] 2020-09-18 18:38
Eeks, I can't seem to be able to install that. Logs: https://dpaste.org/Ek6v

**Comment by urschrei** [comment] 2020-09-22 14:12
@utkarsh2102 0.6.25 is on PyPI now, if you'd like to try…

**Comment by utkarsh2102** [comment] 2020-09-22 14:28
Hi,

With v0.6.25, there's no `illegal hardware instruction` or `core dump`! 🎉 
However, see this:
```
>>> from convertbng.util import convert_bng, convert_lonlat
>>> import numpy as np
>>> lons = [1.0, 3.0]
>>> lats = [2.0, 4.0]
>>> lons
[1.0, 3.0]
>>> lats
[2.0, 4.0]
>>> res_list = convert_bng(lons, lats)
>>> res_list
([nan, nan], [nan, nan])
```

Is `([nan, nan], [nan, nan])` expected?

**Comment by utkarsh2102** [comment] 2020-09-22 14:29
Alternatively,
```
>>> coords = [[1.0, 2.0], [3.0, 4.0]]
>>> a, b = list(zip(*coords))
>>> a
(1.0, 3.0)
>>> b
(2.0, 4.0)
>>> res = convert_bng(a,b)
>>> res
([nan, nan], [nan, nan])
```

**Comment by urschrei** [comment] 2020-09-22 14:33
@utkarsh2102 Ah, that's because the library checks the bounding box, and those coordinates fall outside it. My fault for using them in the README example.

**Comment by urschrei** [comment] 2020-09-22 14:34
@EarthSenseOli @metaljoe @hellicott This seems to be resolved – let me know if you get a chance to test it.

**Comment by utkarsh2102** [comment] 2020-09-22 14:59
Aye, thanks for your work, @urschrei!
I'm sure you can close the issue. If this still seems to be a problem, it can still be re-opened :)

**Comment by metaljoe** [comment] 2020-09-23 10:51
Yep, thanks @urschrei - just tested out the new version and it all works fine. Nice one!

**Comment by urschrei** [comment] 2020-09-23 10:52
@metaljoe Great, thanks for letting me know!

**Closed by urschrei** 2020-09-23 10:52 UTC
